### ISSUE TITLE
Should the stream error and session error be in different number spaces?

### ISSUE THREAD

**Issue by huitema** [afrind/draft-frindell-webtrans-devious-baton#1]
The draft defines "stream errors" and "application errors":

Stream error  | Code | Description
-- | -- | --
IDC | 0x01 | I don't care about this stream

Session error  | Code | Description
-- | -- | --
DA_YAMN | 0x01 | There is insufficient stream credit to continue the protocol

In QUIC, the parameters of both "RESET" and "APPLICATION CLOSE" are in the same application error space -- which would make IDC and DA_YAMN to be the same code. Is that expected?

**Comment by afrind** [comment]
That was the intention.  At first I had separate codes, but realized that the stream error codes didn't make sense in the session context and vice versa.  Rather than add language to make it a protocol error to use the wrong error code, I collapsed the number space so it is not possible.

I'll close this but please reopen if there's a problem with this design.
